// packages/bs-web-component-ng/projects/bs-web-app-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'bs-web-app-angular';
}

<bs-alert
  type="primary"
  [dismissible]="true"
  (bsOnClose)="bsOnClose($event)"
>
  <div>这是一个弹窗</div>
</bs-alert>
<bs-alert
  type="secondary"
  [dismissible]="false"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>
<bs-alert
  type="success"
  [dismissible]="true"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>
<bs-alert
  type="danger"
  [dismissible]="true"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>
<bs-alert
  type="warning"
  [dismissible]="true"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>
<bs-alert
  type="info"
  [dismissible]="true"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>
<bs-alert
  type="light"
  [dismissible]="true"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>
<bs-alert
  type="dark"
  [dismissible]="true"
  message="A simple primary alert—check it out!"
  (bsOnClose)="bsOnClose($event)"
></bs-alert>

<!--<router-outlet></router-outlet>-->

// packages/bs-web-app-vue3/src/App.vue
<template>
    <div>
        <bs-alert :bsOptions='option' :type="type" dismissible="true" message="一个简单的初级警报，看看吧！"></bs-alert>
        <bs-alert :bsOptions="option" type="secondary"></bs-alert>
        <bs-alert :bsOptions="option" type="success"></bs-alert>
        <bs-alert :bsOptions="option" type="danger"></bs-alert>
        <bs-alert :bsOptions="option" type="warning"></bs-alert>
        <bs-alert :bsOptions="option" type="info"></bs-alert>
        <bs-alert :bsOptions="option" type="light"></bs-alert>
        <bs-alert :bsOptions="option" type="dark"></bs-alert>
    </div>
</template>
<script setup lang="ts">
const props = defineProps({
    title: String
})
const option ={
    message: "A simple primary alert—check it out!",
    dismissible: true
};
const type="primary"
// let options ="123";
</script>
